image: node:18  # Usamos la imagen oficial de Node.js

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install -g @angular/cli
    - npm ci
    - ng build --prod --base-href "https://dannschvertt.gitlab.io/sanaya/"
  artifacts:
    paths:
      - dist/sanaya
  only:
    - publicacion  # O cualquier rama que utilices para deploy

